# Default Theme
# Source: PRD v4.9 - Section 6.1

theme:
  id: default
  name: "Default"
  description: "중립적인 기본 블루 테마"

colors:
  primary: "#2563EB"      # 주요 강조색 (블루)
  secondary: "#3B82F6"    # 보조 강조색 (밝은 블루)
  accent: "#DBEAFE"       # 하이라이트 (연한 블루)
  background: "#FFFFFF"   # 배경색
  surface: "#F8FAFC"      # 카드/패널 배경
  dark_text: "#1E293B"    # 본문 텍스트
  light: "#FFFFFF"        # 밝은 텍스트
  gray: "#94A3B8"         # 음소거 요소

typography:
  heading_font: "Arial"
  body_font: "Arial"
  korean_font: "Malgun Gothic"

style_hints:
  rounded_corners: 8
  shadow_blur: 4
