# Default Theme
# 기본 중립 테마 - 특정 브랜드 색상 없음

theme:
  id: default
  name: "Default"
  description: "중립적인 기본 테마"

colors:
  # Core semantic colors (design tokens)
  primary: "#2563EB"        # 블루 - 주요 강조색
  secondary: "#3B82F6"      # 라이트 블루 - 보조 강조색
  accent: "#DBEAFE"         # 페일 블루 - 하이라이트
  background: "#FFFFFF"     # 흰색 배경
  surface: "#F9FAFB"        # 카드/패널 배경
  dark_text: "#1F2937"      # 본문 텍스트 (다크 그레이)
  light: "#FFFFFF"          # 밝은 텍스트 (흰색)
  gray: "#6B7280"           # 음소거 요소

  # Extended palette
  accent2: "#93C5FD"        # 스카이 블루
  accent3: "#EFF6FF"        # 아이스 블루
  border: "#E5E7EB"         # 경계선 색상

typography:
  heading_font: "Arial"
  body_font: "Arial"
  korean_font: "Malgun Gothic"
  heading_weight: bold
  body_weight: normal

style_hints:
  rounded_corners: 8        # 기본 모서리 반경
  shadow_blur: 4            # 그림자 블러
  border_width: 1           # 테두리 두께
  card_padding: 20          # 카드 내부 여백
